# Generated by Django 2.0 on 2019-06-25 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='user',
            new_name='author',
        ),
    ]
