# Generated by Django 2.0 on 2019-06-25 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20190625_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='author',
            new_name='user',
        ),
    ]
