# Generated by Django 2.0 on 2019-06-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20190625_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
