# Generated by Django 2.0 on 2019-06-27 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='amount',
        ),
    ]
